### ISSUE TITLE
Multiple Submissions

### ISSUE THREAD

**Issue by arky** [ooni/test-lists-ui#22]
You can not add more than one submission per session. 

Testcase
==========
1. Login 
2. Select a country 
3. Add a submission and click submit 
4. Try making another submission, you will be returned back to this 'Submitted' form. 

The expected behavior is allow users to do multiple contributions 

![Screenshot 2022-04-04 at 14-05-44 Url Submission](https://user-images.githubusercontent.com/808895/161491521-5f53fda2-ab09-49df-92d2-cc313fb77853.png)

**Comment by arky** [comment]
I think you are not allowed to submitted any contributions if you have already open PR? @sarathms 

{
	"pr_url": "https://github.com/citizenlab/test-lists/pull/949",
	"state": "PR_OPEN"
}

**Comment by agrabeli** [comment]
Thanks @arky for your feedback.

Generally, that's intentional (only being able to do 1 submission at a time), as it requires that the pull request from the submission is merged before you can contribute another submission. Otherwise there's the risk of git conflict (with too many overlapping submissions, without previous pull requests being merged first).

We therefore recommend doing all the changes you want in 1 submission, as opposed to creating a submission for every change (e.g. 1 new URL added).

But your feedback highlights an important point, that we should do a better job at explaining why users can only contribute 1 submission at a time, while encouraging them to add all their contributions in 1 submission.
